# GitHub action - most simple run with cron every day at 700

name: RunTestContainer
on: 
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 7 * * *'
jobs:
  TestcontainerPullAndRun:
    runs-on: ubuntu-latest
    steps:
      - name: Docker run testcontainer from GitHub packages  
        run: docker container run -w /e2e ghcr.io/sim007/testingwithcontainers:main
